"""Make LocationID nullable in Doctor table

Revision ID: 058930200a2c
Revises: fd5f2d1f7e57
Create Date: 2024-04-01 13:53:31.699290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '058930200a2c'
down_revision: Union[str, None] = 'fd5f2d1f7e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('Appointments')
    # op.drop_table('Reviews')
    # op.drop_table('Patient')
    # op.drop_table('Availability')
    # op.drop_table('Doctor')
    # op.drop_table('PatientAppointment')
    # op.drop_index('idx_LocationID', table_name='Location')
    # op.drop_table('Location')
    # op.drop_index('idx_SpecialtyID', table_name='Specialty')
    # op.drop_table('Specialty')

    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop all tables and indexes
    op.drop_table('Appointments')
    op.drop_table('Reviews')
    op.drop_table('Patient')
    op.drop_table('Availability')
    op.drop_table('Doctor')
    op.drop_table('PatientAppointment')
    op.drop_table('Location')
    op.drop_table('Specialty')

